[package]
name = "testrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tendermint-proto = { version = "0.23.9" }
prost = { version = "0.10", default-features = false }
